name: reservastion
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # firebase_core: ^2.25.5
  firebase_core: ^2.9.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.5.2
  flutter_admin_scaffold: ^1.2.0
  image_picker: ^1.1.1
  firebase_storage: ^11.0.14
  gallery_picker: ^0.5.1
  permission_handler: ^11.3.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mua.png
